/*
 * sdp_ctrl_client_errors.h
 *
 *  Created on: Apr 4, 2016
 *      Author: hydrolucid3
 */

#ifndef SDP_ERRORS_H_
#define SDP_ERRORS_H_

enum {
    SDP_SUCCESS = 0,
    SDP_ERROR_MEMORY_ALLOCATION = 0x8000,
    SDP_ERROR_FILESYSTEM_OPERATION,
    SDP_ERROR_ABSOLUTE_PATH,
    SDP_ERROR_PROC_EXISTS,
    SDP_ERROR_UNINITIALIZED,
    SDP_ERROR_CONFIG,
    SDP_ERROR_FORK,
    SDP_ERROR_SYSLOG,
    SDP_ERROR_BAD_ARG,
    SDP_ERROR_SPA,
    SDP_ERROR_CONN_FAIL,
    SDP_ERROR_CONN_DOWN,
    SDP_ERROR_GET_HOST,
    SDP_ERROR_GETADDRINFO,
    SDP_ERROR_SSL,
    SDP_ERROR_SSL_HANDSHAKE,
    SDP_ERROR_SSL_NO_CERT_RECEIVED,
    SDP_ERROR_KEY,
    SDP_ERROR_CERT,
    SDP_ERROR_FIELD_NOT_PRESENT,
    SDP_ERROR_INVALID_MSG,
    SDP_ERROR_INVALID_MSG_SHORT,
    SDP_ERROR_INVALID_MSG_LONG,
    SDP_ERROR_KEEP_ALIVE,
    SDP_ERROR_CRED_REQ,
    SDP_ERROR_ACC_REQ,
    SDP_ERROR_MANY_FAILED_REQS,
    SDP_ERROR_STATE,
    SDP_ERROR_SOCKET,
    SDP_ERROR_SOCKET_OPTION,
    SDP_ERROR_SOCKET_READ,
    SDP_ERROR_SOCKET_WRITE,
    SDP_ERROR_STRTOL,
    SDP_ERROR_STRTOLD,
    SDP_ERROR_KEY_SAVE,
    SDP_ERROR_EXIT_FAILURE,
    SDP_ERROR_GOT_EXIT_SIG,
    SDP_ERROR
};

#define IS_SDP_ERROR(x) (x & 0x8000)


#endif /* SDP_ERRORS_H_ */
